"""empty message

Revision ID: 067b1923f6a6
Revises: ea8e4019eea3
Create Date: 2020-09-01 16:00:49.942387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067b1923f6a6'
down_revision = 'ea8e4019eea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='videos_pkey')
    )
    # ### end Alembic commands ###
