"""empty message

Revision ID: 45edd52b6f42
Revises: 71b4a4419bed
Create Date: 2020-09-01 17:57:49.293236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45edd52b6f42'
down_revision = '71b4a4419bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
